# Path to the directory with the train data
train_dir: data/train/

# Name of the file to save results
fname_to_save: data/default_trck_brk_drp.npz

# Fraction of the validation subset of data
val_size: 0.2

# Random seed
random_seed: 13

vertex: "vertex.json"

# Debug mode
debug: #False
  debug_size: 500

# distribution of tracks' lengths. Use '-1' for following dataset's initial distribution
distribution:
  len3: -1
  len4: -1
  len5: -1
  len6: -1

