# basic visualization of network run on one event


df:
  df_path: '../data/data_radial_2.csv'
  event_ids: ['3'] # ['1..10'] (list of events with these indexes) or [':'] (all events from df)
  read_only_first_lines: 6193
  drop_broken_tracks: True # drop tracks with the gaps or which does not start at station #0


visualize:
  mode: '3d' # '3d'
  ellipses: True

network: #False
  network_path: "results/cloud__init-67-.val_point_in_ellipse.0.95.hdf5"

z_stations: [32.85, 65.25, 96.65, 129.35, 161.25, 193.85]

stations_sizes : [
    [[-1.5, -4.5, 66, 41]],
    [[-1.5, -4.5, 66, 41]],
    [[-1.5, -4.5, 66, 41]],
    # module 0, module 1 FIXED RECTS ON STATION 5 and 6
    [[27.7, -4.5, 66, 41], [-34.7, -4.3, 66, 41]],
    [[40.8, -6.9, 81.6, 45], [-40.8, -6.9, 81.6, 45]],
    [[40.8, -6.9, 81.6, 45], [-40.8, -6.9, 81.6, 45]]]

with_vertex:
  vertex_fname: "data/test/vertex.json"

